[project]
site_name = "Dance Docs"
site_url = "https://jakegatsby.github.io/dance/"
extra_css = ["stylesheets/extra.css"]

nav = [
    { "Home" = "index.md" },
    { "Syllabi" =  [
        { "Bolero" = "syllabus/bolero.md" },
        { "East Coast Swing" = "syllabus/east-coast-swing.md" },
        { "Foxtrot" = "syllabus/foxtrot.md" },
        { "Hustle" = "syllabus/hustle.md" },
    ]},
]

[project.theme.palette]
media = "(prefers-color-scheme: dark)"
scheme = "slate"



